[workspace]
authors = ["Damien GUESDON <kisai.dg.slu@gmail.com>"]
channels = ["conda-forge"]
name = "fakenews_killer"
platforms = ["linux-64", "osx-64"]
version = "0.1.0"

[tasks]
lint = "ruff check ."
fmt = "ruff format ."

[dependencies]
python = "3.10.*"
beautifulsoup4 = "*"
selenium = "*"
selenium-manager = "*"
playwright = "*"
playwright-install = "*"
requests = "*"
lxml = "*"
airflow = "*"
streamlit = "*"
pandas = "*"
pytest = "*"
ruff = "*"